config/routes.rb
Rails.application.routes.draw do
  root to: "gossip#index"
  get 'gossip/index'
  get 'gossip/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/team", to: "student#index"
  get "/contacts", to: "student#contacts"
  get "/welcome/:first_name", to:  "student#welcome"
  
  resources :gossip
  resources :student
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :join_gossip_tags
    has_many :tag, through: :join_gossip_tags
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_gossip_tags
    has_many :gossips, through: :join_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city 
    has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @date = @gossip.created_at.to_date
  end

  
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @gossips = @user.gossips
    end

    def contacts
    end

    def welcome
        @user = User.where(first_name: params[:first_name]).first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/views/gossip/index.html.erb
<h1 class="mb-5">Bienvenue sur The Hacking Gossip</h1>
<div class="container">
    <% @gossips.each do |gossip| %>
        <div>
            <h2><a href=<%= gossip_path(gossip) %>><%= gossip.title %></a></h2>
            <p><em>written by <a href="<%= student_path(gossip.user_id) %>"><%= gossip.user.first_name%></a></em></p>
        </div>
    <% end %>
</div>

app/views/gossip/show.html.erb
<h1><%= @gossip.title%></h1>
<p>Written by <%= link_to "#{@gossip.user.first_name}", student_path(@gossip.user_id) %></p>
<p class="m5 p3 xshadow border border-light"><%= @gossip.content %></p>
<p><em class='text-grey'> - created the <%= @date%> -</em></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

  <body>
  <header class='jumbotron bg-primary text-white d-flex flex-column align-items-center justify-content-center p-5'>
    <a href="<%= root_path %>" class="mt-1 ms-2 position-absolute top-0 start-0 text-white">Accueil</a>
    <h1 class=''>Mon Super Header !</h1>
    <p>Bootstrap is the most popular HTML, CSS, and JS framework for developing
    responsive, mobile-first projects on the web.</p>
    <div class='col-6 d-flex align-items-center justify-content-around'>
      <button class='btn btn-warning border border-secondary col-4'><%= link_to "Contacts", "/contacts" %></button>
      <button class='btn btn-warning border border-secondary col-4'><%= link_to "Team", team_path %></button>
    </div>
  </header>
  <div class="p-5 d-flex flex-column align-items-center">
    <%= yield %>
  </div>
  </body>
</html>

app/views/student/contacts.html.erb
<h1>Contactez les membres de notre équipe</h1>
<h3>incoyableemaildelateam@thp.com</h3>

app/views/student/index.html.erb
<h1><u>Voici la team :</u></h1>
<div class="container xaxa ">
  <% @users.each do |user| %>
    <div class="text-wrap border border-2 rounded-3 border-primary m-3 p-3 col-3">
      <h2 class="text-center  pb-2 border-bottom border-dark">
        <a href="<%= student_path(user) %>"><%= user.last_name %><br>
        <%= user.first_name %></a>
      </h2>
      <p><%= user.description %></p>
    </div>
  <% end %>
</div>

app/views/student/show.html.erb
<h1 class="mb-5">Bienvenue sur le profil de <%= @user.first_name %> <%= @user.last_name %> !</h1>
<div class="container col-6 d-flex flex-column align-items-center">
    <h4><%= @user.age %> ans, <%= @user.city.name %></h4>
    <p><em><%= @user.email%></em></p>


    <p class="align-self-start"><strong>description :</strong></p>
    <p class="align-self-start"><%=@user.description %></p>
    <br />
    <br />
    <div class="container p-0">
        <p><strong>Liste des gossips publiés :</strong></p>
        <p><% @gossips.each do |gossip| %><p>
            <%= link_to "#{gossip.title}", gossip_path(gossip) %>
        <% end %>
    </div>
</div>

app/views/student/welcome.html.erb
<h1>Bienvenue <%= @user.first_name %> !</h1>